CREATE TABLE ADDRESS (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  DISTRICT VARCHAR,
  CITY VARCHAR NOT NULL,
  STREET VARCHAR NOT NULL,
  HOUSE VARCHAR NOT NULL,
  SECTION VARCHAR,
  FLAT VARCHAR NOT NULL,
  ZIP VARCHAR
);

CREATE TABLE CONTACT (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  PHONE VARCHAR NOT NULL,
  EMAIL VARCHAR,
  VK VARCHAR,
  SKYPE VARCHAR,
  FACEBOOK VARCHAR,
  TWITTER VARCHAR,
  ICQ VARCHAR
);

CREATE TABLE DISCOUNT (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR NOT NULL,
  VALUE INTEGER NOT NULL,
  DESCRIPTION VARCHAR
);

CREATE TABLE PASSPORT (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  COUNTRY VARCHAR NOT NULL,
  SERIES VARCHAR NOT NULL DEFAULT '',
  num VARCHAR NOT NULL,
  issued_by VARCHAR NOT NULL,
  issue_date DATE NOT NULL,
  SUBDIVISION VARCHAR
);

CREATE TABLE POST (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR NOT NULL,
  DESCRIPTION VARCHAR
);

CREATE TABLE SERVICE (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  NAME VARCHAR NOT NULL,
  COST NUMERIC(38) NOT NULL,
  DURATION INTEGER NOT NULL,
  DESCRIPTION VARCHAR
);

CREATE TABLE post_service (
  ID BIGINT NOT NULL PRIMARY KEY,
  post_id BIGINT NOT NULL,
  service_id BIGINT NOT NULL,
  FOREIGN KEY (post_id) REFERENCES POST (ID),
  FOREIGN KEY (service_id) REFERENCES SERVICE (ID)
);

CREATE TABLE PERSON (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  SURNAME VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  PATRONYMIC VARCHAR,
  birth_date DATE,
  passport_id BIGINT,
  reg_address_id BIGINT,
  live_address_id BIGINT,
  contact_id BIGINT NOT NULL,
  FOREIGN KEY (passport_id) REFERENCES PASSPORT (ID),
  FOREIGN KEY (reg_address_id) REFERENCES ADDRESS (ID),
  FOREIGN KEY (live_address_id) REFERENCES ADDRESS(ID),
  FOREIGN KEY (contact_id) REFERENCES CONTACT (ID)
);

CREATE TABLE CLIENT (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  person_id BIGINT NOT NULL,
  reg_date DATE NOT NULL,
  discount_id BIGINT,
  in_blacklist BOOLEAN NOT NULL,
  FOREIGN KEY (person_id) REFERENCES PERSON (ID),
  FOREIGN KEY (discount_id) REFERENCES DISCOUNT (ID)
);

CREATE TABLE MASTER (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  person_id BIGINT NOT NULL,
  hiring_date DATE,
  post_id BIGINT NOT NULL
);

CREATE TABLE SCHEDULE (
  ID BIGINT NOT NULL PRIMARY KEY,
  CREATED TIMESTAMP,
  MODIFIED TIMESTAMP,
  VERSION INTEGER NOT NULL,
  reg_date DATE NOT NULL,
  reg_time TIME NOT NULL,
  SURNAME VARCHAR NOT NULL,
  NAME VARCHAR NOT NULL,
  PHONE VARCHAR NOT NULL,
  master_id BIGINT,
  service_id BIGINT NOT NULL,
  STATUS VARCHAR NOT NULL,
  NOTE VARCHAR
);

ALTER TABLE CONTACT ADD CONSTRAINT UNQ_CONTACT_0 UNIQUE (phone);
ALTER TABLE DISCOUNT ADD CONSTRAINT UNQ_DISCOUNT_0 UNIQUE (name);
ALTER TABLE PASSPORT ADD CONSTRAINT UNQ_PASSPORT_0 UNIQUE (series, num);
ALTER TABLE POST ADD CONSTRAINT UNQ_POST_0 UNIQUE (name);
ALTER TABLE SERVICE ADD CONSTRAINT UNQ_SERVICE_0 UNIQUE (name);
ALTER TABLE post_service ADD CONSTRAINT UNQ_post_service_0 UNIQUE (post_id, service_id);

CREATE SEQUENCE address_id_seq START WITH 1;
CREATE SEQUENCE discount_id_seq START WITH 1;
CREATE SEQUENCE passport_id_seq START WITH 1;
CREATE SEQUENCE post_id_seq START WITH 1;
CREATE SEQUENCE contact_id_seq START WITH 1;
CREATE SEQUENCE service_id_seq START WITH 1;
CREATE SEQUENCE post_service_id_seq START WITH 1;
CREATE SEQUENCE person_id_seq START WITH 1;
CREATE SEQUENCE client_id_seq START WITH 1;
CREATE SEQUENCE master_id_seq START WITH 1;
CREATE SEQUENCE schedule_id_seq START WITH 1;